services:
  example_pipeline_yolo:
    build: 
      context: .
      dockerfile: ../../../x86.dockerfile
    volumes:
      - ../../../data/coco:/home/gadget/data/
      - ./weights:/home/gadget/pipeline/trt-engines/
      - ./outputs:/home/gadget/outputs/
      - ./pipeline_class.py:/home/gadget/pipeline/pipeline_class.py
      - ./pipeline_def.json:/home/gadget/pipeline/pipeline_def.json
      - ../../../../pipeline_base.py:/home/gadget/pipeline/pipeline_base.py
      - ../../../../core:/home/gadget/pipeline/core/
      # - ~/projects/LMI_AI_Solutions:/home/gadget/LMI_AI_Solutions
    ipc: host
    runtime: nvidia # https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
    command: python3 pipeline/pipeline_class.py
    