version: "3.9"
services:
  # ---------- platform ----------   
  db:
    container_name: gadget-db
    image: ${DOCKER_REPO}/${DOCKER_PLATFORM}/gadget/postgres:${PACKAGE_VER}
    restart: unless-stopped
    volumes:
      - postgres_db:/var/lib/postgresql/data

  database-api:
    container_name: gadget-database-api
    image: ${DOCKER_REPO}/${DOCKER_PLATFORM}/gadget/database_api:${PACKAGE_VER}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
        
  api-gateway:
    container_name: gadget-api-gateway
    image: ${DOCKER_REPO}/${DOCKER_PLATFORM}/gadget/nginx:${PACKAGE_VER}
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      database-api: 
        condition: service_healthy
      
  gadgetapp:
    container_name: gadget-gadgetapp
    build:
      context: ./gadgetapp
      args:
        DOCKER_PLATFORM: ${DOCKER_PLATFORM}
        PACKAGE_VER: ${PACKAGE_VER}
        PYPI_SERVER: ${PYPI_SERVER}
      dockerfile: gadgetapp.dockerfile
    restart: unless-stopped
    command: /bin/bash init_django_project.bash
    volumes:
      - static_volume:/gadgetapp/staticfiles
      - inline-storage:/gadgetapp/image_archive
    ports:
      - 8085:8000
    depends_on:
      api-gateway:
        condition: service_healthy
  
  nginx:
    container_name: gadget-nginx
    build: 
      context: ./gadgetapp
      dockerfile: nginx.dockerfile
      args:
        DOCKER_PLATFORM: ${DOCKER_PLATFORM}
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - static_volume:/gadgetapp/staticfiles
    depends_on:
      gadgetapp: 
        condition: service_healthy

  data-broker:
    container_name: gadget-data-broker
    image: ${DOCKER_REPO}/${DOCKER_PLATFORM}/gadget/zmq_broker:${PACKAGE_VER}
    restart: unless-stopped
    ports:
      - 5000:5000
      - 5001:5001
    depends_on:
      api-gateway: 
        condition: service_healthy
  
  data-manager:
    container_name: gadget-data-manager
    image: ${DOCKER_REPO}/${DOCKER_PLATFORM}/gadget/data_manager:${PACKAGE_VER}
    restart: unless-stopped
    environment:
      - INLINE_CAPACITY_METRIC=max-content-size
      - INLINE_CAPACITY_THRESHOLD="0.5 GB"
      - OFFLINE_CAPACITY_METRIC=min-storage-free
      - OFFLINE_CAPACITY_THRESHOLD="50 GB"
      - TZ=utc
    volumes:
      - data-manager-storage:/app/data/internal
      - inline-storage:/app/data/inline
      - offline-storage:/app/data/offline
    depends_on:
      api-gateway: 
        condition: service_healthy
  
  system-monitor:
    container_name: gadget-system-monitor
    image: ${DOCKER_REPO}/${DOCKER_PLATFORM}/gadget/system_monitor:${PACKAGE_VER}
    restart: unless-stopped
    volumes:
      - inline-storage:/app/data
    depends_on:
      api-gateway: 
        condition: service_healthy

  # ---------- inspection ----------   
  pipeline:
    container_name: gadget-pipeline
    command: gadget_pipeline_server
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
    build: 
      context: ./pipeline
      args:
        DOCKER_PLATFORM: ${DOCKER_PLATFORM}
        PACKAGE_VER: ${PACKAGE_VER}
        PYPI_SERVER: ${PYPI_SERVER}
      dockerfile: pipeline.dockerfile
    image: pipeline:${PACKAGE_VER}
    restart: unless-stopped
    environment:
      - DATA_BROKER_SUB_TOPICS=sensor/gadget-sensor-gocator/0
      - MODELS_ROOT=/home/gadget/pipeline/models
      - PIPELINE_PATH=/home/gadget/pipeline
      - PIPELINE_CLASS=pipeline_class.ModelPipeline
      - PIPELINE_DEFINITION_JSON=pipeline_def.json
      - PASS_THROUGH_ENABLED=True
      - TZ=utc
    volumes:
      - ./pipeline/:/home/gadget/pipeline
      - inline-storage:/app/data
    depends_on:
      api-gateway: 
        condition: service_healthy

  automation:
    container_name: gadget-automation
    command: gadget_automation_server
    network_mode: "host"
    build:
      context: ./automation
      dockerfile: automation.dockerfile
      args:
        DOCKER_PLATFORM: ${DOCKER_PLATFORM}
        PACKAGE_VER: ${PACKAGE_VER}
        PYPI_SERVER: ${PYPI_SERVER}
    image: automation:${PACKAGE_VER}
    restart: unless-stopped
    environment:
      - DATABASE_API_HOST=127.0.0.1
      - DATA_BROKER_HOST=127.0.0.1
      - DATA_BROKER_SUB_TOPICS=pipeline/gadget-pipeline/0
      - AUTOMATION_PATH=/home/gadget/automation/
      - AUTOMATION_CLASS=automation_class.AutomationClass
      - AUTOMATION_DEFINITION_JSON=automation_class_def.json
      - TZ=utc
    volumes:
      - ./automation:/home/gadget/automation
    depends_on:
      api-gateway: 
        condition: service_healthy

  gocator:
    container_name: gadget-gocator
    network_mode: host 
    image: ${DOCKER_REPO}/${DOCKER_PLATFORM}/gadget/sensor_gocator:${PACKAGE_VER}
    restart: unless-stopped
    environment:
      - DATABASE_API_HOST=127.0.0.1
      - DATA_BROKER_HOST=127.0.0.1
      - CAM_IP=10.11.1.19
      - START=True
      - EMULATION_ENABLED=True
      - TZ=utc
    volumes:
      - ./sensor/test_images:/home/gadget/workspace/test_images
      - inline-storage:/app/data
    depends_on:
      api-gateway: 
        condition: service_healthy


  #---------- gofactory ----------   
  mqtt-bridge:
    container_name: gadget-mqtt-bridge
    image: ${DOCKER_REPO}/${DOCKER_PLATFORM}/gadget/mqtt_bridge:${PACKAGE_VER}
    restart: unless-stopped
    environment:
      - CLIENT_ID=${FACTORY_CLIENT_ID}
      - BROKER_HOSTNAME=${FACTORY_HOST}
      - BROKER_AUTH_USERNAME=root
      - BROKER_AUTH_PASSWORD=um-@cU_-ZNa7zy_dmNcf
    volumes:
      - inline-storage:/app/data/inline
      - offline-storage:/app/data/offline
    depends_on:
      api-gateway: 
        condition: service_healthy
    
  s3-integrator:
    container_name: gadget-s3-integrator
    image: ${DOCKER_REPO}/${DOCKER_PLATFORM}/utils/s3_integrator:${PACKAGE_VER}
    restart: unless-stopped
    ports:
      - 7778:7777
    environment:
      - CLOUD_PROJECT_ID=${CLOUD_PROJECT_ID}
      - STORAGE_PROFILE=${STORAGE_PROFILE}
      - MINIO_HOST=${FACTORY_HOST}
      - VAULT_TOKEN=${VAULT_TOKEN} 
    volumes:
      - offline-storage:/tmp/s3files
  
  log-collector:
    container_name: gadget-log-collector
    image: ${DOCKER_REPO}/${DOCKER_PLATFORM}/utils/log_collector:${PACKAGE_VER}
    restart: unless-stopped
    ports:
      - 7771:7770
    volumes:
      - offline-storage:/tmp/s3files
      - /var/log/journal:/var/log/hostjournal:ro
  
volumes:
  data-manager-storage:
  offline-storage:     
  inline-storage:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/gadget-inline
  postgres_db:
    name: postgres_db
  static_volume:
    name: static_volume