default:
  FACTORY_CLIENT_ID: trevor-dev-0
  GADGET_DEVICE_ID: trevor-0
  VAULT_CREDENTIAL: eWYvjfUbyG9zs8nDhmuuLStM4M9r7uCYjl1IBkahNbvkOz0d4QSzw0nb1tYtcEAX2InFo8Qc
  SUBFOLDER:
  GADGETAPP_TITLE: Test