# Generated by Django 4.0.2 on 2022-09-23 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configs', 'configs_migrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigUI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='UI Configs')),
                ('title', models.CharField(max_length=100)),
                ('media_path_0', models.TextField(default='')),
                ('count', models.IntegerField(blank=True, default=0)),
                ('media_type', models.IntegerField(choices=[(0, 'Image'), (1, 'Point Cloud')], default=0)),
                ('info_display_0_label', models.TextField(default='Class: ')),
                ('info_display_0_value', models.TextField(default='--')),
                ('info_display_1_label', models.TextField(default='Score: ')),
                ('info_display_1_value', models.TextField(default='--')),
                ('info_display_2_label', models.TextField(default='Event: ')),
                ('info_display_2_value', models.IntegerField(default=0)),
                ('plot_0', models.IntegerField(choices=[(0, 'none'), (1, 'line'), (2, 'bar'), (3, 'hist')], default=0)),
                ('plot_0_update', models.IntegerField(choices=[(0, 'absolute'), (1, 'relative')], default=0)),
                ('plot_0_buffer', models.IntegerField(default=25)),
                ('plot_0_xinit', models.CharField(default='nan', max_length=3)),
                ('plot_0_yinit', models.CharField(default='nan', max_length=3)),
                ('plot_0_xlabel', models.CharField(default='x', max_length=128)),
                ('plot_0_ylabel', models.CharField(default='y', max_length=128)),
                ('plot_0_misc', models.TextField(blank=True, default='')),
                ('plot_1', models.IntegerField(choices=[(0, 'none'), (1, 'line'), (2, 'bar'), (3, 'hist')], default=0)),
                ('plot_1_update', models.IntegerField(choices=[(0, 'absolute'), (1, 'relative')], default=0)),
                ('plot_1_buffer', models.IntegerField(default=25)),
                ('plot_1_xinit', models.CharField(default='nan', max_length=3)),
                ('plot_1_yinit', models.CharField(default='nan', max_length=3)),
                ('plot_1_xlabel', models.CharField(default='x', max_length=128)),
                ('plot_1_ylabel', models.CharField(default='y', max_length=128)),
                ('plot_1_misc', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserAutomationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automation_param_1', models.CharField(default='automation param 1 value', max_length=256)),
                ('automation_param_2', models.IntegerField(default=0.0)),
                ('automation_param_3', models.BooleanField(choices=[(False, 'For False'), (True, 'For True')], default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserPipelineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_param_1', models.CharField(default='pipeline param 1 value', max_length=256)),
                ('pipeline_param_2', models.IntegerField(default=0.0)),
                ('pipeline_param_3', models.BooleanField(choices=[(False, 'For False'), (True, 'For True')], default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserSensorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_param_1', models.CharField(default='sensor param 1 value', max_length=256)),
                ('sensor_param_2', models.IntegerField(default=0.0)),
                ('sensor_param_3', models.BooleanField(choices=[(False, 'For False'), (True, 'For True')], default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserSensorSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_sensor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='configs.sensorconfig')),
            ],
        ),
        migrations.CreateModel(
            name='UserPipelineSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_pipeline', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='configs.pipelineconfig')),
            ],
        ),
        migrations.CreateModel(
            name='UserAutomationSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_automation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configs.automationconfig')),
            ],
        ),
    ]
