# Generated by Django 4.0.2 on 2023-05-19 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configs', 'configs_migrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigUI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='UI Configs')),
                ('title', models.CharField(max_length=100)),
                ('media_path_0', models.TextField(default='')),
                ('media_path_1', models.TextField(default='')),
                ('media_path_2', models.TextField(default='')),
                ('media_path_3', models.TextField(default='')),
                ('media_path_4', models.TextField(default='')),
                ('count', models.IntegerField(blank=True, default=0)),
                ('media_type', models.IntegerField(choices=[(0, 'Image'), (1, 'Point Cloud')], default=0)),
                ('info_display_0_label', models.TextField(default='Class: ')),
                ('info_display_0_value', models.TextField(default='--')),
                ('info_display_1_label', models.TextField(default='Score: ')),
                ('info_display_1_value', models.TextField(default='--')),
                ('info_display_2_label', models.TextField(default='Event: ')),
                ('info_display_2_value', models.IntegerField(default=0)),
                ('plot_0', models.IntegerField(choices=[(0, 'none'), (1, 'line'), (2, 'bar'), (3, 'hist')], default=0)),
                ('plot_0_update', models.IntegerField(choices=[(0, 'absolute'), (1, 'relative')], default=0)),
                ('plot_0_buffer', models.IntegerField(default=25)),
                ('plot_0_xinit', models.CharField(default='nan', max_length=3)),
                ('plot_0_yinit', models.CharField(default='nan', max_length=3)),
                ('plot_0_xlabel', models.CharField(default='x', max_length=128)),
                ('plot_0_ylabel', models.CharField(default='y', max_length=128)),
                ('plot_0_misc', models.TextField(blank=True, default='')),
                ('plot_1', models.IntegerField(choices=[(0, 'none'), (1, 'line'), (2, 'bar'), (3, 'hist')], default=0)),
                ('plot_1_update', models.IntegerField(choices=[(0, 'absolute'), (1, 'relative')], default=0)),
                ('plot_1_buffer', models.IntegerField(default=25)),
                ('plot_1_xinit', models.CharField(default='nan', max_length=3)),
                ('plot_1_yinit', models.CharField(default='nan', max_length=3)),
                ('plot_1_xlabel', models.CharField(default='x', max_length=128)),
                ('plot_1_ylabel', models.CharField(default='y', max_length=128)),
                ('plot_1_misc', models.TextField(blank=True, default='')),
                ('plot_2', models.IntegerField(choices=[(0, 'none'), (1, 'line'), (2, 'bar'), (3, 'hist')], default=0)),
                ('plot_2_update', models.IntegerField(choices=[(0, 'absolute'), (1, 'relative')], default=0)),
                ('plot_2_buffer', models.IntegerField(default=25)),
                ('plot_2_xinit', models.CharField(default='nan', max_length=3)),
                ('plot_2_yinit', models.CharField(default='nan', max_length=3)),
                ('plot_2_xlabel', models.CharField(default='x', max_length=128)),
                ('plot_2_ylabel', models.CharField(default='y', max_length=128)),
                ('plot_2_misc', models.TextField(blank=True, default='')),
                ('plot_3', models.IntegerField(choices=[(0, 'none'), (1, 'line'), (2, 'bar'), (3, 'hist')], default=0)),
                ('plot_3_update', models.IntegerField(choices=[(0, 'absolute'), (1, 'relative')], default=0)),
                ('plot_3_buffer', models.IntegerField(default=25)),
                ('plot_3_xinit', models.CharField(default='nan', max_length=3)),
                ('plot_3_yinit', models.CharField(default='nan', max_length=3)),
                ('plot_3_xlabel', models.CharField(default='x', max_length=128)),
                ('plot_3_ylabel', models.CharField(default='y', max_length=128)),
                ('plot_3_misc', models.TextField(blank=True, default='')),
                ('gocator_0_url', models.TextField(blank=True, default='')),
                ('gocator_1_url', models.TextField(blank=True, default='')),
                ('gocator_2_url', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserAutomationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_defect', models.BooleanField(choices=[(False, 'For False'), (True, 'For True')], default=False)),
                ('external_start', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPipelineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(default='gadget-pipeline', max_length=256)),
                ('instance', models.IntegerField(default=0)),
                ('od_confidence_board', models.FloatField(default=0.5)),
                ('od_confidence_defect', models.FloatField(default=0.5)),
                ('od_confidence_water', models.FloatField(default=0.5)),
                ('ad_error_threshold', models.FloatField(default=25)),
                ('ad_error_size', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserSensorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(default='gadget-sensor-avt', max_length=256)),
                ('instance', models.IntegerField(default=0)),
                ('timed_trigger_mode', models.BooleanField(choices=[(False, 'External'), (True, 'Time Based')], default=False)),
                ('trigger_delay', models.IntegerField(default=0.0)),
                ('exposure_time', models.FloatField(default=2.0)),
                ('gain', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='UserSensorSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_sensor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='configs.sensorconfig')),
            ],
        ),
        migrations.CreateModel(
            name='UserPipelineSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_pipeline', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='configs.pipelineconfig')),
            ],
        ),
        migrations.CreateModel(
            name='UserAutomationSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_automation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configs.automationconfig')),
            ],
        ),
    ]
