# Generated by Django 4.0.2 on 2022-11-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpipelineconfig',
            name='pipeline_param_1',
        ),
        migrations.RemoveField(
            model_name='userpipelineconfig',
            name='pipeline_param_2',
        ),
        migrations.RemoveField(
            model_name='userpipelineconfig',
            name='pipeline_param_3',
        ),
        migrations.RemoveField(
            model_name='usersensorconfig',
            name='sensor_param_1',
        ),
        migrations.RemoveField(
            model_name='usersensorconfig',
            name='sensor_param_2',
        ),
        migrations.RemoveField(
            model_name='usersensorconfig',
            name='sensor_param_3',
        ),
        migrations.AddField(
            model_name='userpipelineconfig',
            name='confidence_leg',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='usersensorconfig',
            name='exposure_time',
            field=models.FloatField(default=200.0),
        ),
        migrations.AddField(
            model_name='usersensorconfig',
            name='gain',
            field=models.FloatField(default=20.0),
        ),
    ]
