# Generated by Django 4.0.2 on 2022-05-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userautomationconfig',
            old_name='mark_cojoin',
            new_name='mark_defect',
        ),
        migrations.RenameField(
            model_name='userpipelineconfig',
            old_name='confidence_cojoin',
            new_name='confidence_defect',
        ),
        migrations.RemoveField(
            model_name='userautomationconfig',
            name='mark_filling',
        ),
        migrations.RemoveField(
            model_name='userautomationconfig',
            name='mark_misform',
        ),
        migrations.RemoveField(
            model_name='userautomationconfig',
            name='mark_underfill',
        ),
        migrations.RemoveField(
            model_name='userpipelineconfig',
            name='confidence_filling',
        ),
        migrations.RemoveField(
            model_name='userpipelineconfig',
            name='confidence_misform',
        ),
        migrations.RemoveField(
            model_name='userpipelineconfig',
            name='confidence_sausage',
        ),
        migrations.RemoveField(
            model_name='userpipelineconfig',
            name='confidence_underfill',
        ),
    ]
