# Generated by Django 4.0.2 on 2022-06-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_alter_configui_plot_0_alter_configui_plot_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpipelineconfig',
            name='confidence_defect',
        ),
        migrations.AddField(
            model_name='userpipelineconfig',
            name='padim_thres_z',
            field=models.FloatField(default=20),
        ),
    ]
